source_Incoming_Mail_Server:imap.gmail.com
source_mail_port:993
source_Sender_E_mail:akash.giri@adeptia.com
source_mail_subject:AG_Mail_Source_Basic_IMAP_TLS_Vault_Config
source_mail_file_name:Contact.xml
target_Outgoing_Mail_Server:smtp.gmail.com
target_mail_port:587
target_From_Email-Id:acsectest@adeptia.com
target_To_Email_Id:akash.giri@adeptia.com
target_mail_subject:AG_Mail_Target_Basic_SMTP_TLS_Vault_Config
target_mail_file_name:AG_Mail_Target_Basic_SMTP_TLS_Vault_Config.xml
event_Incoming_Mail_Server:imap.gmail.com
event_mail_port:993
event_Sender_E_mail:akash.giri@adeptia.com
event_mail_subject:AG_Basic_IMAP_TLS_Vault_Config_Event
event_mail_file_name:androiD.xml
